spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234abcd
    url: jdbc:mysql://127.0.0.1:3306/holiroo?userSSL=false
  jpa:
    show-sql: true
    database: mysql
    #database-platform: org.hibernate.dialect.MySQLDialect
  #jackson:
    #default-property-inclusion:

#server:
  #context-path: /nswrentie